### ISSUE TITLE
Wrong endpoints generated in jungle.config.js

### ISSUE THREAD

**Issue by str** [eosdac/eosdac-api#1]
After running the factory script, it generates a jungle.config.js with wrong endpoints

```
        endpoint: 'http://jungle2.$MYDAC.io,
        wsEndpoint: 'ws://jungle2.$MYDAC.io',
```

**Comment by michaeljyeates** [comment]
Wrong repo, ill move

**Comment by lukestokes** [comment]
Thanks @str. This should now be resolved here https://github.com/eosdac/eosdac-factory/issues/4

I also updated the README with some more information.
