### ISSUE TITLE
filler stuck at 59728747

### ISSUE THREAD

**Issue by ghost** [eosdac/eosdac-api#2]
![Screenshot from 2019-05-26 07-20-08](https://user-images.githubusercontent.com/33427521/58442257-09967c00-80af-11e9-806f-8b56fca58c4c.png)

tried this:
pm2 delete all
pm2 start
CONFIG=mainnet ./eosdac-filler.js -r -s 59727000
filler still gets stuck

also re-ran CONFIG=mainnet node ./watchers/replay.js
watcher seems to run through ok (though there was one error reading proposal near 59346219)

**Comment by ghost** [comment]
using latest commit, and eosio-statereceiver latest commit
pm2 error logs not showing anything
I purged the rabbitmq queues, didn't help

**Comment by michaeljyeates** [comment]
you shouldnt need to start the filler with -r and -s, it can be done via pm2 once things are up and running

**Comment by michaeljyeates** [comment]
can you post your mainnet.config.js file here please

**Comment by ghost** [comment]
![Screenshot from 2019-05-28 00-02-44](https://user-images.githubusercontent.com/33427521/58452174-049bf180-80dc-11e9-81db-188fd4962e0e.png)

**Comment by ghost** [comment]
![Screenshot from 2019-05-28 00-23-32](https://user-images.githubusercontent.com/33427521/58452961-d966d180-80de-11e9-940d-f4669ca2a471.png)

**Comment by piecesnbits** [comment]
to reproduce: start filler on current block and confirm that everything works by casting a custodian vote (verify that it is caught). 
next propose a custodian contract config change via msig. confirm that it's not added "proposal not found"

**Comment by michaeljyeates** [comment]
Can you check the cpu usage while running pm2.

There seem to be 2 problems here and I cannot reproduce either, the filler hanging is different to "proposal not found".

I am going to investigate what is happening with the transaction listed because it is not a dac related msig

**Comment by michaeljyeates** [comment]
It would help to copy and paste the block and transaction id of the propose action which created the update config proposal, please dont send screenshots because i have to manually type it in

**Comment by michaeljyeates** [comment]
Once we know the block of the transaction which is failing to store we can run the following command

`CONFIG=mainnet ./eosdac-filler.js -t [block_number]`

This will attempt to fetch the single block, it should put it into the queue and the processor should output something

**Comment by michaeljyeates** [comment]
You can keep the pm2 processor running when you run the filler manually (the pm2 filler can run too), run logs on the processor with this command

`pm2 logs [pm2 process number]`

**Comment by ghost** [comment]
the following block number hangs:
CONFIG=mainnet ./eosdac-filler.js -t 59728751

![Screenshot from 2019-05-28 06-43-39](https://user-images.githubusercontent.com/33427521/58475592-ff5a9900-8113-11e9-885b-7d5e74f6193d.png)

top shows CPU less than 1% for each of the 8 running node processes and mongod

**Comment by ghost** [comment]
![Screenshot from 2019-05-28 08-06-09](https://user-images.githubusercontent.com/33427521/58480236-8b25f280-811f-11e9-891a-7a8b03591fcb.png)
^ CONFIG=mainnet ./eosdac-filler.js -t 59728751
(with added console logging to eosio-statereceiver/connections.js)
getting some nulls there like this_block, then statereceiver.receivedBlock does nothing and just returns.
it just hangs there, no errors in the pm2 logs

statereceiver seems to process only nulls for block numbers >= 59728751

**Comment by andrew-p-bryan** [comment]
regarding missing msigs:

watcher/replay.js says "Error getting proposal" for this msig:
awhnl.yvetyj 
d2b1882564d64f399542d3da07d77f4db2cc0032d2f7c580ad15f0afc737a667

watcher/replay.js skips with no error for this msig:
k5rfmln11zor 
82999940673419ec930db8bfea85c7e180e8eb87bdb0decd63e9c2406436fbca

**Comment by ghost** [comment]
switched to a different eosdac state history node, and the filler works a charm. thanks @piecesnbits for that suggestion on telegram.
